using YoutubeMusic.NET.Services;
using YoutubeMusic.NET.Common.Source.Interfaces;
using YoutubeMusic.NET.Common.Models;
using YoutubeMusic.NET.Common.Services;


namespace YoutubeMusic.NET.UI;

public partial class MainForm
{
    private async void OnPlaylistDoubleClick()
    {
        if (playlistsListBox.SelectedItem != null)
        {
            try
            {
                var selectedIndex = playlistsListBox.SelectedIndex;
                if (selectedIndex >= 0 && selectedIndex < _playlists.Count)
                {
                    var selectedPlaylist = _playlists[selectedIndex];
                    
                    SimpleLogger.Info($"Loading playlist: {selectedPlaylist.Name}");
                    
                    // Load playlist songs
                    var songs = await LoadPlaylistSongsAsync(selectedPlaylist);
                    
                    if (songs.Count > 0)
                    {
                        // Display songs in playlist view
                        UpdatePlaylistDisplay(songs);
                        
                        // Switch to playlist tab
                        mainTabControl.SelectedTab = playlistTabPage;
                        
                        SimpleLogger.Info($"Loaded {songs.Count} songs from playlist: {selectedPlaylist.Name}");
                    }
                    else
                    {
                        SimpleLogger.Warn($"No songs found in playlist: {selectedPlaylist.Name}");
                        SafeInvoke(() => MessageBox.Show(
                            $"No songs were found in the playlist '{selectedPlaylist.Name}'.\n\nNote: Some library playlists (like 'New Episodes' or autogenerated ones) may not be accessible without full authentication.", 
                            "Playlist Empty", 
                            MessageBoxButtons.OK, 
                            MessageBoxIcon.Information));
                    }
                }
            }
            catch (Exception ex)
            {
                SimpleLogger.Error(ex, "Failed to load playlist");
            }
        }
    }

    private async Task<List<Song>> LoadPlaylistSongsAsync(Playlist playlist)
    {
        try
        {
            // Use YouTube Music source provider
            var sourceProvider = _sourceProvider;
            
            if (sourceProvider != null && sourceProvider.PlaylistService.IsAvailable)
            {
                // Load songs from the playlist
                var songs = await sourceProvider.PlaylistService.GetPlaylistSongsAsync(playlist.Id);
                return songs;
            }
            else
            {
                // If we can't find the source provider, return the songs that are already in the playlist
                return playlist.Songs;
            }
        }
        catch (Exception ex)
        {
            SimpleLogger.Error(ex, $"Failed to load songs for playlist: {playlist.Name}");
            return new List<Song>();
        }
    }

    private async void LoadPlaylists()
    {
        try
        {
            SimpleLogger.Info("Loading playlists...");
            playlistsListBox.Items.Clear();
            _playlists.Clear();
            
            // Use YouTube Music source provider
            if (_sourceProvider != null && _sourceProvider.PlaylistService != null)
            {
                var provider = _sourceProvider;
            {
                try
                {
                    // Check if provider is available and has a playlist service
                    if (provider.IsAvailable && provider.PlaylistService?.IsAvailable == true)
                    {
                        SimpleLogger.Info($"Loading playlists from {provider.Name}...");
                        var providerPlaylists = await provider.PlaylistService.LoadUserPlaylistsAsync();
                        
                        foreach (var playlist in providerPlaylists)
                        {
                            _playlists.Add(playlist);
                        }
                        
                        SimpleLogger.Info($"Loaded {providerPlaylists.Count} playlists from {provider.Name}");
                    }
                    else
                    {
                        SimpleLogger.Debug($"Skipping {provider.Name} - not available or no playlist service");
                    }
                }
                catch (Exception ex)
                {
                    SimpleLogger.Warn(ex, $"Failed to load playlists from {provider.Name}");
                }
            }
            
            // Also search for public playlists if no user playlists were found
            if (_playlists.Count == 0)
            {
                SimpleLogger.Info("No user playlists found, searching for public playlists...");
                await LoadPublicPlaylists();
            }

            // Sort playlists by name
            var sortedPlaylists = _playlists.OrderBy(p => p.Name).ToList();
            playlistsListBox.Items.Clear();
            foreach (var playlist in sortedPlaylists)
            {
                var display = playlist.SongCount > 0 
                    ? $"{playlist.Name} ({playlist.SongCount})" 
                    : playlist.Name;
                playlistsListBox.Items.Add(display);
            }
            // Replace _playlists with sorted list
            _playlists.Clear();
            _playlists.AddRange(sortedPlaylists);

            SimpleLogger.Info($"Total playlists loaded: {_playlists.Count}");
            foreach (var playlist in _playlists)
            {
                SimpleLogger.Info($"Playlist: Name='{playlist.Name}', Id='{playlist.Id}', Author='{playlist.Author}', Songs={playlist.SongCount}");
            }

            // Auto-select startup playlist
            _ = Task.Run(async () => {
                // Wait a bit for UI to settle
                await Task.Delay(500);
                
                var startupPlaylist = _playlists.FirstOrDefault(p => 
                    p.Id == "LM" || 
                    p.Id == "saved_songs" ||
                    p.Name.Equals("Liked songs", StringComparison.OrdinalIgnoreCase) || 
                    p.Name.Equals("Liked Music", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("Saved Songs", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("saved_songs", StringComparison.OrdinalIgnoreCase));

                if (startupPlaylist != null)
                {
                    SafeInvoke(() => {
                        var index = _playlists.IndexOf(startupPlaylist);
                        if (index >= 0)
                        {
                            playlistsListBox.SelectedIndex = index;
                            OnPlaylistDoubleClick();
                        }
                    });
                }
            });
            }
        }
        catch (Exception ex)
        {
            SimpleLogger.Error(ex, "Failed to load playlists");
        }
    }

    private async Task LoadPublicPlaylists()
    {
        try
        {
            if (_sourceProvider != null && _sourceProvider.PlaylistService?.IsAvailable == true)
            {
                var provider = _sourceProvider;
                // Search for popular playlists
                var searchTerms = new[] { "top hits", "popular", "trending", "best" };
                
                foreach (var searchTerm in searchTerms)
                {
                    var publicPlaylists = await provider.PlaylistService.SearchPlaylistsAsync(searchTerm, 5);
                    
                    foreach (var playlist in publicPlaylists)
                    {
                        // Avoid duplicates
                        if (!_playlists.Any(p => p.Id == playlist.Id))
                        {
                            _playlists.Add(playlist);
                            playlistsListBox.Items.Add(playlist.Name);
                        }
                    }
                }
            }
        }
        catch (Exception ex)
        {
            SimpleLogger.Error(ex, "Failed to load public playlists");
        }
    }

    private async Task ReloadPlaylists()
    {
        try
        {
            SimpleLogger.Info("Reloading playlists...");
            
            
            // Call the existing LoadPlaylists method
            LoadPlaylists();
            
            SimpleLogger.Info("Playlists reloaded successfully");
            
        }
        catch (Exception ex)
        {
            SimpleLogger.Error(ex, "Failed to reload playlists");
            
        }
    }
}
